[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpackage-lock.json.backup[m[36m:[m[1;31m<<<<<<<[m HEAD
Binary file [35mpackage-lock.zip[m matches
[35mpublic/404.html[m[36m:[m[1;31m<<<<<<<[m HEAD
[35mpublic/404.html[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/.env[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/authController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/authController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/authController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/examController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/controllers/userController.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/middleware/auth.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/models/Question.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/models/Question.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package-lock.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/package.json[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/routes/examRoutes.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/seed.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/server.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/server.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/sampleBackend/server.js[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/user.ts[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/api/user.ts[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/components/layout/Footer.tsx[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/components/layout/Footer.tsx[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/components/layout/Footer.tsx[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/components/layout/Header.tsx[m[36m:[m[1;31m<<<<<<<[m HEAD
[35msrc/components/layout/Header.tsx[m[36m:[m[1;31m<<<<<<<[m HEAD
